services:
    manyacg:
        container_name: manyacg
        image: ghcr.io/krau/manyacg:latest
        restart: unless-stopped
        volumes:
            - ./cache:/opt/manyacg/cache
            - ./logs:/opt/manyacg/logs
            - ./downloads:/opt/manyacg/downloads
        env_file:
            - .env
