on:
    push:
        tags:
            - 'v*'
        branches:
            - main

permissions:
    contents: write
    packages: write

jobs:
    releases-matrix:
        name: Release Go Binary
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]
        

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Release Go Binary
              uses: wangyoucao577/go-release-action@v1
              with:
                pre_command: export CGO_ENABLED=0
                goos: ${{ matrix.goos }}
                goarch: ${{ matrix.goarch }}
                github_token: ${{ secrets.GITHUB_TOKEN }}
                extra_files: |
                    LICENSE
                    README.md
                ldflags: -s -w
                binary_name: ManyACG
